version: "3.9"

services:
  milvus:
    image: milvusdb/milvus:v2.6.1
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      COMMON_STORAGETYPE: "local"
      DEPLOY_MODE: "STANDALONE"
    ports:
      - "9091:9091"
      - "19530:19530"

  attu:
    image: zilliz/attu:v2.6
    container_name: attu
    environment:
      MILVUS_URL: "http://milvus:19530"
    ports:
      - "8000:3000"
    depends_on:
      - milvus
