# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
    nodejs: "latest"
  # We recommend using a requirements file for reproducible builds.
  # This is just a quick example to get started.
  # https://docs.readthedocs.io/page/guides/reproducible-builds.html
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install -r docs/requirements.txt


mkdocs:
  configuration: mkdocs.yml