[workspace]
members = [
    "raphtory",
    "raphtory-benchmark",
    "examples/rust",
    "examples/netflow",
    "examples/custom-gql-apis",
    "python",
    "raphtory-graphql",
    "raphtory-auth-noop",
    "raphtory-server",
    "raphtory-api",
    "raphtory-core",
    "raphtory-storage",
    "raphtory-api-macros",
    "raphtory-tests",
    "raphtory-itertools",
    "drop-logging",
    "raphtory-graphql-tests"]
default-members = ["raphtory"]
resolver = "2"

[workspace.package]
version = "0.18.0"
documentation = "https://raphtory.readthedocs.io/en/latest/"
repository = "https://github.com/Raphtory/raphtory/"
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/Raphtory/raphtory/"
keywords = ["graph", "temporal-graph", "temporal"]
authors = ["Pometry"]
rust-version = "1.95.0"
edition = "2021"
categories = ["science", "database-implementations", "data-structures"]

# debug symbols are using a lot of resources
[profile.dev]
split-debuginfo = "unpacked"
debug = 1
opt-level = 1

[profile.release-with-debug]
inherits = "release"
debug = true

# use this if you really need debug symbols
[profile.with-debug]
inherits = "dev"
debug = true
opt-level = 0

# for fast one-time builds (e.g., docs/CI)
[profile.build-fast]
inherits = "dev"
debug = false
incremental = false
opt-level = 1 # much smaller files


[workspace.dependencies]
db4-graph = { version = "0.18.0", path = "db4-graph", default-features = false }
db4-storage = { version = "0.18.0", path = "db4-storage" }
raphtory = { version = "0.18.0", path = "raphtory", default-features = false }
raphtory-tests = { path = "raphtory-tests", default-features = false }
raphtory-api = { version = "0.18.0", path = "raphtory-api", default-features = false }
raphtory-api-macros = { version = "0.18.0", path = "raphtory-api-macros", default-features = false }
raphtory-core = { version = "0.18.0", path = "raphtory-core", default-features = false }
raphtory-graphql = { version = "0.18.0", path = "raphtory-graphql", default-features = false }
raphtory-storage = { version = "0.18.0", path = "raphtory-storage", default-features = false }
raphtory-itertools = { version = "0.18.0", path = "raphtory-itertools" }
drop-logging = { version = "0.18.0", path = "drop-logging" }
async-graphql = { version = "7.2.1", features = ["dynamic-schema"] }
async-graphql-poem = "7.2.1"
dynamic-graphql = "0.10.2"
derive_more = "2.1.1"
tikv-jemallocator = "0.7.0"
reqwest = { version = "0.13.4", default-features = false, features = [
    "multipart",
    "json",
    "rustls",
] }
boxcar = "0.2.14"
iter-enum = { version = "1.2.1", features = ["rayon"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", features = ["float_roundtrip"] }
pyo3 = { version = "0.29.0", features = ["multiple-pymethods", "chrono"] }
pyo3-build-config = "0.29.0"
pyo3-arrow = { package = "raphtory-pyo3-arrow", version = "0.19.0" }
numpy = "0.29.0"
itertools = "0.15.0"
rand = "0.9.4"
quick_cache = "0.7.0"
rayon = "1.12.0"
roaring = "0.11.4"
tokio = { version = "1.50.0", features = ["full"] }
once_cell = "1.21.4"
parking_lot = { version = "0.12.5", features = [
    "serde",
    "arc_lock",
    "send_guard",
] }
ordered-float = "5.3.0"
chrono = { version = "0.4.44", features = ["serde"] }
chrono-tz = "0.10.4"
tempfile = "3.27.0"
futures-util = "0.3.32"
thiserror = "2.0.18"
dotenvy = "0.15.7"
csv = "1.4.0"
flate2 = "1.1.9"
regex = "1.12.3"
num-traits = "0.2.19"
num-integer = "0.1"
rand_distr = "0.5.1"
rustc-hash = "2.1.1"
twox-hash = "2.1.2"
tinyvec = { version = "1.11", features = ["serde", "alloc"] }
lock_api = { version = "0.4.14", features = ["arc_lock", "serde"] }
dashmap = { version = "6.1.0", features = ["serde", "rayon"] }
glam = "0.33.0"
quad-rand = "0.2.3"
zip = "8.6.0"
bzip2 = "0.6.1"
async-trait = "0.1.89"
async-openai = "0.28.3"
num = "0.4.3"
display-error-chain = "0.2.2"
bigdecimal = { version = "0.4.10", features = ["serde"] }
kdam = "0.6.4"
hashbrown = { version = "0.17.1" }
pretty_assertions = "1.4.1"
streaming-stats = "0.2.3"
proptest = "1.11.0"
proptest-derive = "0.8.0"
criterion = "0.8.2"
crossbeam-channel = "0.5.15"
base64 = "0.23.0"
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"] }
spki = "0.8.0"
poem = { version = "3.1.12", features = ["compression", "embed", "static-files"] }
rust-embed = { version = "8.11.0", features = ["interpolate-folder-path"] }
opentelemetry = "0.32.0"
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic"] }
opentelemetry-stdout = "0.32.0"
tracing = { version = "0.1.44", features = ["log"] }
tracing-opentelemetry = "0.33.0"
tracing-subscriber = { version = "0.3.23", features = ["std", "env-filter"] }
indoc = "2.0.7"
walkdir = "2"
config = "0.15.23"
either = "1.16.0"
clap = { version = "4.6.0", features = ["derive", "env"] }
memmap2 = { version = "0.9.11" }
ahash = { version = "0.8.12", features = ["serde"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
ouroboros = "0.18.5"
url = "2.5"
lazy_static = "1.5.0"
pest = "2.8.6"
pest_derive = "2.8.6"
minijinja = "2.18.0"
minijinja-contrib = { version = "2.18.0", features = ["datetime"] }
lancedb = { version = "0.33.0", features = [] }
heed = "0.22.0"
sqlparser = "0.62.0"
futures = "0.3"
arrow = { version = "58.4.0" }
parquet = { version = "58.4.0" }
arrow-json = { version = "58.4.0" }
arrow-buffer = { version = "58.4.0" }
arrow-schema = { version = "58.4.0" }
arrow-csv = { version = "58.4.0" }
arrow-array = { version = "58.4.0", features = ["chrono-tz"] }
arrow-cast = { version = "58.4.0" }
arrow-ipc = { version = "58.4.0" }
arrow-data = { version = "58.4.0" }
arrow-select = { version = "58.4.0" }
serde_arrow = { version = "0.14.2", features = ["arrow-58"] }
datafusion = { version = "54.1.0" }
datafusion-physical-expr-common = "54.1.0"
datafusion-physical-expr = "54.1.0"
datafusion-physical-plan = "54.1.0"
datafusion-expr-common = "54.1.0"
moka = { version = "0.12.15", features = ["future"] }
indexmap = { version = "2.13.0", features = ["rayon"] }
fake = { version = "5.1.0", features = ["chrono"] }
strsim = { version = "0.11.1" }
uuid = { version = "1.22.0", features = ["v4"] }
bitvec = "1.0.1"
sysinfo = "0.39.3"
strum = "0.28.0"
strum_macros = "0.28.0"
pythonize = { version = "0.29.0" }
test-log = "0.2.19"
axum = "0.8.9"
serde-diff = "0.4.1"
field_types = "1.1.0"
opentelemetry-appender-tracing = "0.32.0"
mock-collector = "0.2.14"

[workspace.dependencies.storage]
package = "db4-storage"
path = "db4-storage"

[workspace.dependencies.auth]
package = "raphtory-auth-noop"
path = "raphtory-auth-noop"
