version: "3.9"
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  query:
    image: raphtory-core-it:latest
    environment:
      RAPHTORY_JAVA_RUN_CLASS: com.raphtory.service.Query
      RAPHTORY_ZOOKEEPER_ADDRESS: zoo1:2181
      RAPHTORY_PARTITIONS_SERVERCOUNT: 2
      RAPHTORY_DATA: /raphtory/data_it/
    volumes:
      - "./it/src/it/resources:/raphtory/data_it:z"
      - "./it/target/docker:/tmp/raphtory:z"
  cluster:
    image: raphtory-core-it:latest
    ports:
      - 1736:1736
    environment:
      RAPHTORY_JAVA_RUN_CLASS: com.raphtory.service.ClusterManager
      RAPHTORY_ZOOKEEPER_ADDRESS: zoo1:2181
      RAPHTORY_PARTITIONS_SERVERCOUNT: 2
      RAPHTORY_DATA: /raphtory/data_it/
    volumes:
      - "./it/src/it/resources:/raphtory/data_it:z"
      - "./it/target/docker:/tmp/raphtoryTest:z"
  ingestion:
    image: raphtory-core-it:latest
    environment:
      RAPHTORY_JAVA_RUN_CLASS: com.raphtory.service.Ingestion
      RAPHTORY_ZOOKEEPER_ADDRESS: zoo1:2181
      RAPHTORY_PARTITIONS_SERVERCOUNT: 2
      RAPHTORY_DATA: /raphtory/data_it/
    volumes:
      - "./it/src/it/resources:/raphtory/data_it:z"
      - "./it/target/docker:/tmp/raphtoryTest:z"
  partition:
    image: raphtory-core-it:latest
    deploy:
      replicas: 2
    environment:
      RAPHTORY_JAVA_RUN_CLASS: com.raphtory.service.Partition
      RAPHTORY_ZOOKEEPER_ADDRESS: zoo1:2181
      RAPHTORY_PARTITIONS_SERVERCOUNT: 2
      RAPHTORY_DATA: /raphtory/data_it/
    volumes:
      - "./it/src/it/resources:/raphtory/data_it:z"
      - "./it/target/docker:/tmp/raphtoryTest:z"
