[package]
name = "docbrown"
description = "DocBrown, a temporal graph library"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# arrow2 = { version ="0.16", features = ["compute"] }
# crossbeam = "0.8"
# crossbeam-utils = "0.8"
# mimalloc = "0.1"
# mimalloc = { version = "0.1", default-features = false }
bincode = "1"
bzip2 = "0.4"
chrono = "0.4"
csv = "1.1.6"
flate2 = "1.0"
flume = "0.10"
futures = {version = "0.3", features = ["thread-pool"] }
genawaiter = "0.99"
itertools="0.10"
num-traits = "0.2"
openssl = { version = "0.10", features = ["vendored"] }
parking_lot = { version = "0.12" , features = ["serde", "arc_lock"] }
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1"
regex = "1"
replace_with = "0.1"
reqwest = { version = "0.11.14", features = ["blocking"] }
roaring={ version = "0.10", features = ["serde"] }
rustc-hash = "1.1.0"
serde = { version = "1", features = ["derive","rc"] }
sorted_vector_map = "0.1"
tempdir = "0.3"
tokio = { version = "1.27.0", features = ["full"] }
thiserror = "1"
twox-hash = "1.6.3"
uuid = { version = "1.3.0", features = ["v4"] }
neo4rs = "0.6.0"

[dev-dependencies]
criterion = "0.4"
csv = "1"
pretty_assertions = "1"
quickcheck = "1"
quickcheck_macros = "1"

[[bench]]
name = "tgraph_benchmarks"
harness = false

[[bench]]
name = "base"
harness = false

[[bench]]
name = "parameterized"
harness = false

[[bench]]
name = "graph_ops"
harness = false

[[bench]]
name = "algobench"
harness = false


# [profile.release]
# debug = 1

# [rust]
# debuginfo-level = 1
