[package]
name = "raphtory-graphql"
description = "Raphtory GraphQL server"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true

[dependencies]
raphtory = { workspace = true, features = [
    "io",
] }
tempfile = { workspace = true }
raphtory-api = { workspace = true }
raphtory-storage = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = { workspace = true }
spki = { workspace = true }
thiserror = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
poem = { workspace = true }
tokio = { workspace = true }
async-graphql = { workspace = true, features = ["apollo_tracing"] }
dynamic-graphql = { workspace = true }
async-graphql-poem = { workspace = true }
futures-util = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["http-json", "http-proto", "reqwest-rustls", "tls-aws-lc", "reqwest-blocking-client", "internal-logs"] }
opentelemetry-stdout = { workspace = true }
opentelemetry-appender-tracing = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
rustc-hash = { workspace = true }
rayon = { workspace = true }
ahash = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
bigdecimal = { workspace = true, features = ["serde"] }
quick_cache = { workspace = true }
field_types = { workspace = true }
pythonize = { workspace = true, optional = true }

# python binding optional dependencies
pyo3 = { workspace = true, optional = true }
crossbeam-channel = { workspace = true }
zip = { workspace = true }
clap = { workspace = true }
rust-embed = { workspace = true }
typetag = { workspace = true }

[dev-dependencies]
parking_lot = { workspace = true }
tempfile = { workspace = true }
pretty_assertions = { workspace = true }
arrow = { workspace = true }
parquet = { workspace = true }


[features]
default = []
vectors = ["raphtory/vectors"]
integration-test = ["opentelemetry_sdk/testing"]
python = ["dep:pyo3", "dep:pythonize", "raphtory/python"]
panic-on-drop = ["raphtory/panic-on-drop"]
