from __future__ import annotations

###############################################################################
#                                                                             #
#                      AUTOGENERATED TYPE STUB FILE                           #
#                                                                             #
#    This file was automatically generated. Do not modify it directly.        #
#    Any changes made here may be lost when the file is regenerated.          #
#                                                                             #
###############################################################################

from typing import *
from raphtory import *
import raphtory.filter as filter
from raphtory.algorithms import *
from raphtory.vectors import *
from raphtory.node_state import *
from raphtory.graphql import *
from raphtory.typing import *
import numpy as np
from numpy.typing import NDArray
from datetime import datetime
import pandas
from pandas import DataFrame
import pyarrow  # type: ignore[import-untyped]
from pyarrow import DataType  # type: ignore[import-untyped]
from os import PathLike
import networkx as nx  # type: ignore
import pyvis  # type: ignore
from raphtory.iterables import *

__all__ = ['gql', 'register_procedure', 'GqlResult', 'GqlRow']
def gql(graph: GraphView, query: str, params: Optional[dict] = None) -> GqlResult:
    """
    Execute a GQL query against a Raphtory graph view.

    Args:
        graph (GraphView): A Raphtory GraphView to query.
        query (str): A GQL query string.
        params (dict, optional): Optional parameter bindings for the query. Defaults to None.

    Returns:
        GqlResult: A result object with table display, pandas conversion, and iteration.
    """

def register_procedure(graph: GraphView, name: str, input_params: list[str], output_params: list[str], data: list[dict]) -> None:
    """
    Register a mock procedure with the cached coordinator.

    Args:
        graph (GraphView): A Raphtory GraphView (needed to ensure coordinator is initialized).
        name (str): Procedure name (e.g., "test.my.proc").
        input_params (list[str]): List of input parameter names.
        output_params (list[str]): List of output parameter names.
        data (list[dict]): List of dicts, each dict maps column name -> value.

    Returns:
        None:
    """

class GqlResult(object): 
    """GQL query result with table display, pandas conversion, and iteration."""

    def __getitem__(self, key):
        """Return self[key]."""

    def __iter__(self):
        """Implement iter(self)."""

    def __len__(self):
        """Return len(self)."""

    def __repr__(self):
        """Return repr(self)."""

    def __str__(self):
        """Return str(self)."""

    @property
    def columns(self) -> list[str]:
        """
        Get column names.

        Returns:
            list[str]:
        """

    def num_columns(self) -> int:
        """
        Number of columns.

        Returns:
            int:
        """

    def num_rows(self) -> int:
        """
        Number of rows.

        Returns:
            int:
        """

    def to_df(self) -> pandas.DataFrame:
        """
        Convert to a pandas DataFrame.

        Returns:
            pandas.DataFrame:
        """

class GqlRow(object): 
    """A single row from a GQL query result."""

    def __getitem__(self, key):
        """Return self[key]."""

    def __repr__(self):
        """Return repr(self)."""

    def keys(self) -> list[str]:
        """
        Column names of this row.

        Returns:
            list[str]:
        """

    def to_dict(self) -> dict:
        """
        Convert this row to a Python `dict` of `{column: value}`.

        Returns:
            dict:
        """

    def values(self) -> list:
        """
        Values of this row aligned with `keys()`.

        Returns:
            list:
        """
