from __future__ import annotations

###############################################################################
#                                                                             #
#                      AUTOGENERATED TYPE STUB FILE                           #
#                                                                             #
#    This file was automatically generated. Do not modify it directly.        #
#    Any changes made here may be lost when the file is regenerated.          #
#                                                                             #
###############################################################################

from typing import *
from raphtory import *
import raphtory.filter as filter
from raphtory.algorithms import *
from raphtory.vectors import *
from raphtory.node_state import *
from raphtory.graphql import *
from raphtory.typing import *
import numpy as np
from numpy.typing import NDArray
from datetime import datetime
from pandas import DataFrame
from pyarrow import DataType  # type: ignore[import-untyped]
from os import PathLike
import networkx as nx  # type: ignore
import pyvis  # type: ignore
from raphtory.iterables import *

__all__ = ["gql", "GqlResult", "GqlRow"]

def gql(graph: Any, query: Any):
    """
    Execute a GQL query against a Raphtory graph view.

    Args:
        graph: A Raphtory GraphView to query
        query: A GQL query string

    Returns:
        A GqlResult object with table display, pandas conversion, and iteration.
    """

class GqlResult(object):
    """GQL query result with table display, pandas conversion, and iteration."""

    def __getitem__(self, key):
        """Return self[key]."""

    def __iter__(self):
        """Implement iter(self)."""

    def __len__(self):
        """Return len(self)."""

    def __repr__(self):
        """Return repr(self)."""

    def __str__(self):
        """Return str(self)."""

    @property
    def columns(self):
        """Get column names."""

    def num_columns(self):
        """Number of columns."""

    def num_rows(self):
        """Number of rows."""

    def to_df(self):
        """Convert to a pandas DataFrame."""

class GqlRow(object):
    """A single row from a GQL query result."""

    def __getitem__(self, key):
        """Return self[key]."""

    def __repr__(self):
        """Return repr(self)."""

    def keys(self): ...
    def to_dict(self): ...
    def values(self): ...
