{
 "title": "Raphtory Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "GraphID", "query": { "query": "label_values(graphID)" } },
   { "name": "SourceID", "query": { "query": "label_values(sourceID)" } },
   { "name": "PartitionID", "query": { "query": "label_values(partitionID)" } },
   { "name": "JobID", "query": { "query": "label_values(jobID)" } }
  ]
 },
 "panels": [
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tuples Parsed by Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "source_total_tuples_processed_total",
     "legendFormat": "{{graphID}} Source {{sourceID}}"
    }
   ]
  },
  {
   "title": "Updates Produced by Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "source_vertex_add_total{graphID=~\"$GraphID\", sourceID=~\"$SourceID\"}",
     "legendFormat": "{{graphID}} Source {{sourceID}} -  Vertex Adds"
    },
    {
     "expr": "source_edge_add_total{graphID=~\"$GraphID\", sourceID=~\"$SourceID\"}",
     "legendFormat": "{{graphID}} Source {{sourceID}} - Edge Adds"
    }
   ]
  },
  {
   "title": "Errors in Source Parsing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "source_total_source_errors_total{graphID=~\"$GraphID\", sourceID=~\"$SourceID\"}",
     "legendFormat": "{{graphID}} Source {{sourceID}}"
    }
   ]
  },
  {
   "title": "Vertex Adds Processed by Partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "partition_vertex_adds_total{graphID=~\"$GraphID\", partitionID=~\"$PartitionID\"}",
     "legendFormat": "{{graphID}} Partition {{partitionID}} Vertex Adds"
    }
   ]
  },
  {
   "title": "Edge Adds Processed by Partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "partition_edge_adds_total{graphID=~\"$GraphID\", partitionID=~\"$PartitionID\"}",
     "legendFormat": "{{graphID}} Partition {{partitionID}} Edge Adds"
    }
   ]
  },
  { "title": "Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Queries Submitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "query_manager_queries_spawned_total{graphID=~\"$GraphID\"}",
     "legendFormat": "{{graphID}} Queries"
    }
   ]
  },
  {
   "title": "Total Perspectives Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "query_handler_perspectives_processed_total{graphID=~\"$GraphID\", jobID=~\"$JobID\"}",
     "legendFormat": "{{graphID}} Perspectives for {{jobID}}"
    }
   ]
  },
  {
   "title": "Total Graph Opperations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "query_handler_graph_operations_total{graphID=~\"$GraphID\", jobID=~\"$JobID\"}",
     "legendFormat": "{{graphID}} Perspectives for {{jobID}}"
    }
   ]
  },
  {
   "title": "Total Table Opperations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "query_handler_table_operations_total{graphID=~\"$GraphID\", jobID=~\"$JobID\"}",
     "legendFormat": "{{graphID}} Perspectives for {{jobID}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "query_handler_sent_messages_total{graphID=~\"$GraphID\", jobID=~\"$JobID\"}",
     "legendFormat": "{{graphID}} Perspectives for {{jobID}}"
    }
   ]
  }
 ]
}