{% set name = "pyraphtory" %}
{% set version = "0.1.0" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/Raphtory/Raphtory.git
  git_tag: feature/DEV-1144-conda-package

build:
  number: {{ build_number }}

requirements:
  host:
    - git
    - openjdk ==11.0.13
    - python ==3.10.4
    - python-build
    - poetry
    - pip
    - sbt
    - setuptools
  run:
    - openjdk ==11.0.13
    - python ==3.10.4
    - sbt


about:
  home: https://github.com/raphtory/raphtory/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Raphtory python API, Temporal Graph analytics

extra:
  recipe-maintainers:
    - Pometry-Team