{% set name = "pyraphtory" %}
{% set version = "0.1.0" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../../
#  url: file:///vagrant_data/python/pyraphtory/dist/pyraphtory-0.0.1.tar.gz
#  sha256: efed2398b378552280591766a2cf06f695f903d24452932afb46d8aa91a465f3
#  git_rev: v0.1.0
#  git_url: https://github.com/Raphtory/Raphtory.git

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - gcc
    - git
    - openjdk ==11.0.13
    - python >=3.6,<3.11
    - python-build
    - poetry
    - pip
    - sbt
    - setuptools
  run:
    - openjdk ==11.0.13
    - python >=3.6,<3.11
    - python-build
    - sbt

test:
  imports:
    - pyraphtory

about:
  home: https://github.com/raphtory/raphtory/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Raphtory python API, Temporal Graph analytics

extra:
  recipe-maintainers:
    - Pometry-Team