from __future__ import annotations

###############################################################################
#                                                                             #
#                      AUTOGENERATED TYPE STUB FILE                           #
#                                                                             #
#    This file was automatically generated. Do not modify it directly.        #
#    Any changes made here may be lost when the file is regenerated.          #
#                                                                             #
###############################################################################

from typing import *
from raphtory import *
from raphtory.algorithms import *
from raphtory.vectors import *
from raphtory.node_state import *
from raphtory.graphql import *
from raphtory.typing import *
from datetime import datetime
from pandas import DataFrame
from os import PathLike
import networkx as nx  # type: ignore
import pyvis  # type: ignore
from raphtory.iterables import *

__all__ = [
    "FilterExpr",
    "FilterOps",
    "PropertyFilterOps",
    "Node",
    "NodeIdFilterBuilder",
    "NodeNameFilterBuilder",
    "NodeTypeFilterBuilder",
    "Edge",
    "EdgeEndpoint",
    "EdgeEndpointIdFilter",
    "EdgeEndpointNameFilter",
    "EdgeEndpointTypeFilter",
    "ExplodedEdge",
]

class FilterExpr(object):
    def __and__(self, value):
        """Return self&value."""

    def __invert__(self):
        """~self"""

    def __or__(self, value):
        """Return self|value."""

    def __rand__(self, value):
        """Return value&self."""

    def __ror__(self, value):
        """Return value|self."""

class FilterOps(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def all(self): ...
    def any(self): ...
    def avg(self): ...
    def contains(self, value) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if this object contains a specified property.

        Arguments:
            PropValue:

        Returns:
            filter.FilterExpr:
        """

    def ends_with(self, value): ...
    def first(self): ...
    def fuzzy_search(
        self, prop_value: str, levenshtein_distance: int, prefix_match: bool
    ) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if the specified properties approximately match the specified string.

        Uses a specified Levenshtein distance and optional prefix matching.

        Arguments:
            prop_value (str): Property to match against.
            levenshtein_distance (int): Maximum levenshtein distance between the specified prop_value and the result.
            prefix_match (bool): Enable prefix matching.

        Returns:
            filter.FilterExpr:
        """

    def is_in(self, values: list[PropValue]) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if a given value is in a specified iterable of properties.

        Arguments:
            values (list[PropValue]):

        Returns:
            filter.FilterExpr:
        """

    def is_none(self) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if a given value is none.

        Returns:
            filter.FilterExpr:
        """

    def is_not_in(self, values: list[PropValue]) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if a given value is not in a specified iterable of properties.

        Arguments:
            values (list[PropValue]):

        Returns:
            filter.FilterExpr:
        """

    def is_some(self) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if a given value is some.

        Returns:
            filter.FilterExpr:
        """

    def last(self): ...
    def len(self): ...
    def max(self): ...
    def min(self): ...
    def not_contains(self, value) -> filter.FilterExpr:
        """
        Returns a filter expression that checks if this object does not contain a specified property.

        Arguments:
            PropValue:

        Returns:
            filter.FilterExpr:
        """

    def starts_with(self, value): ...
    def sum(self): ...

class PropertyFilterOps(FilterOps):
    def temporal(self): ...

class Node(object):
    @staticmethod
    def id(): ...
    @staticmethod
    def metadata(name): ...
    @staticmethod
    def name(): ...
    @staticmethod
    def node_type(): ...
    @staticmethod
    def property(name): ...
    @staticmethod
    def window(start, end): ...

class NodeIdFilterBuilder(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class NodeNameFilterBuilder(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class NodeTypeFilterBuilder(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class Edge(object):
    @staticmethod
    def dst(): ...
    @staticmethod
    def metadata(name): ...
    @staticmethod
    def property(name): ...
    @staticmethod
    def src(): ...
    @staticmethod
    def window(start, end): ...

class EdgeEndpoint(object):
    def id(self): ...
    def metadata(self, name): ...
    def name(self): ...
    def node_type(self): ...
    def property(self, name): ...

class EdgeEndpointIdFilter(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class EdgeEndpointNameFilter(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class EdgeEndpointTypeFilter(object):
    def __eq__(self, value):
        """Return self==value."""

    def __ge__(self, value):
        """Return self>=value."""

    def __gt__(self, value):
        """Return self>value."""

    def __le__(self, value):
        """Return self<=value."""

    def __lt__(self, value):
        """Return self<value."""

    def __ne__(self, value):
        """Return self!=value."""

    def contains(self, value): ...
    def ends_with(self, value): ...
    def fuzzy_search(self, value, levenshtein_distance, prefix_match): ...
    def is_in(self, values): ...
    def is_not_in(self, values): ...
    def not_contains(self, value): ...
    def starts_with(self, value): ...

class ExplodedEdge(object):
    @staticmethod
    def metadata(name): ...
    @staticmethod
    def property(name): ...
    @staticmethod
    def window(start, end): ...
