# Intergration tests for raphtory-graphql (separate crate to avoid self-dependency with the "integration-test" feature)

[package]
name = "raphtory-graphql-tests"
version.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
categories.workspace = true
publish = false

[dependencies]
raphtory = { workspace = true, features = ["panic-on-drop"] }
raphtory-graphql = { workspace = true, default-features = false, features = ["integration-test", "panic-on-drop"] }
tempfile.workspace = true
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "testing"] }
url.workspace = true
tokio = { workspace = true }
mock-collector = { workspace = true }
typetag = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
dynamic-graphql = { workspace = true }
serde_json = { workspace = true }
