[package]
name = "raphtory_custom_gql_apis"
description = "Python package for raphtory, a temporal graph library"
version = "0.9.3"
keywords = ["graph", "temporal-graph", "temporal", "jira"]
authors = ["Pometry"]
rust-version = "1.75.0"
edition = "2021"

doc = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
[lib]
name = "raphtory"
crate-type = ["cdylib"]

[dependencies]
raphtory_core = { package = "raphtory", path = "../../raphtory", features = ["python", "search", "vectors"] }
raphtory-graphql = { path = "../../raphtory-graphql", features = ["python"] }
raphtory-api = { path = "../../raphtory-api" }
async-graphql = { workspace = true, features = ["dynamic-schema"] }
dynamic-graphql = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["full"] }
pyo3 = { workspace = true, features = ["multiple-pymethods"] }
thiserror = { workspace = true }
display-error-chain = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
itertools = { workspace = true }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[build-dependencies]
pyo3-build-config = { workspace = true }
