[package]
name = "raphtory_custom_gql_apis"
description = "Python package for raphtory, a temporal graph library"
version = "0.9.3"
keywords = ["graph", "temporal-graph", "temporal", "jira"]
authors = ["Pometry"]
rust-version = "1.75.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[lib]
[lib]
name = "_raphtory_custom"
crate-type = ["cdylib"]

[dependencies]
raphtory = { workspace = true, features = ["python"] }
raphtory-graphql = { workspace = true, features = ["python"] }
async-graphql = { workspace = true, features = ["dynamic-schema"] }
futures-util = { workspace = true }
pyo3 = { workspace = true, features = ["multiple-pymethods"] }


[features]
extension-module = ["pyo3/extension-module"]

[build-dependencies]
pyo3-build-config = { workspace = true }
