[package]
name = "lanl"
version.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raphtory = { path = "../../raphtory", features = ["python"], version = "0.8.0" }
raphtory-arrow.workspace = true
raphtory-storage = { path = "../../raphtory-storage", version = "0.8.0" }
pyo3 = "0.20.0"
