import json
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import numpy
import pytest
from raphtory import Graph
from raphtory.vectors import (
    OpenAIEmbeddings,
    VectorCache,
    VectorisedGraph,
    embedding_server,
)

embedding_map = {
    "raphtory": [1.0, 0.0, 0.0],  # this is now needed,
    "node1": [1.0, 0.0, 0.0],
    "node2": [0.0, 1.0, 0.0],
    "node3": [0.0, 0.0, 1.0],
    "node4": [1.0, 1.0, 0.0],
    "edge1": [1.0, 0.1, 0.0],
    "edge2": [0.0, 1.0, 0.1],
    "edge3": [0.0, 1.0, 1.0],
}


@pytest.fixture(autouse=True)
def test_server():
    @embedding_server
    def custom_embeddings(text: str):
        return embedding_map[text]

    with custom_embeddings.start(7340):
        yield


def post_json(url, payload):
    data = json.dumps(payload).encode()
    req = Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(req, timeout=50) as r:
            return r.status, r.read()
    except HTTPError as e:
        return e.code, e.read()


def test_failing_python_embeddings():
    @embedding_server
    def failing_embeddings(text: str):
        assert False

    with failing_embeddings.start(7342):
        payload = {"model": "whatever", "input": ["Hello world"]}
        status, _ = post_json("http://localhost:7342/embeddings", payload)
        assert status == 500
        status, _ = post_json("http://localhost:7342/embeddings", payload)
        assert status == 500


def floats_are_equals(float1: float, float2: float) -> bool:
    return bool(numpy.isclose(float1, float2, rtol=1e-05, atol=1e-08, equal_nan=False))


# the graph generated by this function looks like this:
#
#        edge1
#      ╭─────── node2
#    node1
#      ╰─────── node3  ───── node4
#           edge2             edge3
#
#
def create_graph() -> VectorisedGraph:
    g = Graph()

    g.add_node(1, "node1")
    g.add_node(2, "node2")
    g.add_node(3, "node3")
    g.add_node(4, "node4")

    g.add_edge(2, "node1", "node2", {"name": "edge1"})
    g.add_edge(3, "node1", "node3", {"name": "edge2"})
    g.add_edge(4, "node3", "node4", {"name": "edge3"})

    embeddings = OpenAIEmbeddings(api_base="http://localhost:7340")
    v_cache = VectorCache(embeddings)
    vg = g.vectorise(v_cache, nodes="{{ name }}", edges="{{ properties.name }}")

    return vg


def test_embedding_sever_context_manager():
    @embedding_server
    def constant(text: str):
        return [1.0]

    with constant.start(7341):
        payload = {
            # "model": "whatever",
            "input": ["The text to vectorise"]
        }
        status, body = post_json("http://localhost:7341/embeddings", payload)
        assert status == 200
        result = json.loads(body)
        vector = result["data"][0]["embedding"]
        assert vector == [1.0]


def test_selection():
    vg = create_graph()

    assert len(vg.empty_selection().get_documents()) == 0
    assert len(vg.empty_selection().get_documents_with_distances()) == 0

    nodes_to_select = ["node1", "node2"]
    edges_to_select = [("node1", "node2"), ("node1", "node3")]

    selection = vg.empty_selection()
    selection.add_nodes(nodes_to_select)
    nodes = selection.nodes()
    node_names_returned = [node.name for node in nodes]
    assert node_names_returned == nodes_to_select
    docs = [doc.content for doc in selection.get_documents()]
    assert docs == ["node1", "node2"]

    selection = vg.empty_selection()
    selection.add_edges(edges_to_select)
    edges = selection.edges()
    edge_names_returned = [(edge.src.name, edge.dst.name) for edge in edges]
    assert edge_names_returned == edges_to_select
    docs = [doc.content for doc in selection.get_documents()]
    assert docs == ["edge1", "edge2"]

    edge_tuples = [(edge.src, edge.dst) for edge in edges]
    selection = vg.empty_selection()
    selection.add_nodes(nodes)
    selection.add_edges(edge_tuples)
    nodes_returned = selection.nodes()
    assert nodes == nodes_returned
    edges_returned = selection.edges()
    assert edges == edges_returned


def test_search():
    vg = create_graph()

    assert len(vg.edges_by_similarity("edge1", 10).nodes()) == 0
    assert len(vg.nodes_by_similarity("node1", 10).edges()) == 0

    selection = vg.nodes_by_similarity([1.0, 0.0, 0.0], 1)
    assert [node.name for node in selection.nodes()] == ["node1"]
    assert [doc.content for doc in selection.get_documents()] == ["node1"]

    edges = vg.edges_by_similarity([1.0, 0.0, 0.0], 1).edges()
    edge_names_returned = [(edge.src.name, edge.dst.name) for edge in edges]
    assert edge_names_returned == [("node1", "node2")]
    # TODO: same for edges ?

    [(doc1, distance1)] = vg.entities_by_similarity(
        "node1", 1
    ).get_documents_with_distances()
    assert floats_are_equals(distance1, 0.0)
    assert (doc1.entity.name, doc1.content) == ("node1", "node1")

    # chained search
    node_selection = vg.nodes_by_similarity("node2", 1)
    edge_selection = vg.edges_by_similarity("node3", 1)
    entity_selection = vg.entities_by_similarity("node1", 4)
    docs = (
        node_selection.append(edge_selection)
        .append(entity_selection)
        .get_documents()[:4]
    )
    assert [doc.content for doc in docs] == ["node2", "edge3", "node1", "edge1"]
    # the intention of this test was getting all the documents of for different entities,
    # including at least node and one edge at the top.
    # However, we don't have a way currently of taking the documents of the first N entities
    # we could have a method selection.limit_entities()
    # or we could also have a method entity.get_documents for the entities we return (not trivial)


def test_expansion():
    vg = create_graph()

    selection = vg.entities_by_similarity("node1", 1)
    selection.expand(2)
    assert len(selection.get_documents()) == 5
    assert len(selection.nodes()) == 3
    assert len(selection.edges()) == 2

    selection = vg.entities_by_similarity("node1", 1)
    selection.expand_entities_by_similarity("edge1", 1)
    selection.expand_entities_by_similarity("node2", 1)
    assert len(selection.get_documents()) == 3
    nodes = selection.nodes()
    node_names_returned = [node.name for node in nodes]
    assert node_names_returned == ["node1", "node2"]
    edges = selection.edges()
    edge_names_returned = [(edge.src.name, edge.dst.name) for edge in edges]
    assert edge_names_returned == [("node1", "node2")]

    selection = vg.empty_selection()
    selection.expand_entities_by_similarity("node3", 10)
    assert len(selection.get_documents()) == 0

    selection = vg.entities_by_similarity("node1", 1)
    selection.expand_entities_by_similarity("node3", 10)
    assert len(selection.get_documents()) == 7
    assert len(selection.nodes()) == 4
    assert len(selection.edges()) == 3
    # TODO: add some expand_documents here


def test_windows():
    vg = create_graph()

    selection = vg.nodes_by_similarity("node1", 1, (4, 5))
    assert [doc.content for doc in selection.get_documents()] == ["node4"]

    selection = vg.nodes_by_similarity("node4", 1, (1, 2))
    assert [doc.content for doc in selection.get_documents()] == ["node1"]

    selection.expand(10, (0, 3))
    contents = [doc.content for doc in selection.get_documents()]
    assert contents == ["node1", "edge1", "node2"]

    # this leave the selection unchanged, as only edge3 and node4 exist
    selection.expand_entities_by_similarity("node1", 100, (4, 100))
    contents = [doc.content for doc in selection.get_documents()]
    assert contents == ["node1", "edge1", "node2"]

    selection.expand(10, (3, 100))
    contents = [doc.content for doc in selection.get_documents()]
    assert contents == ["node1", "edge1", "node2", "edge2", "node3", "edge3", "node4"]


def test_filtering_by_entity_type():
    vg = create_graph()

    selection = vg.empty_selection()
    selection.add_nodes(["node1"])
    selection.expand_nodes_by_similarity("node2", 10)
    contents = [doc.content for doc in selection.get_documents()]
    assert contents == ["node1", "node2", "node3", "node4"]

    selection = vg.empty_selection()
    selection.add_edges([("node1", "node2")])
    selection.expand_edges_by_similarity("edge3", 10)
    contents = [doc.content for doc in selection.get_documents()]
    assert contents == ["edge1", "edge2", "edge3"]


@embedding_server
def constant_embedding(_text):
    return [1.0, 0.0, 0.0]


def test_default_template():
    g = Graph()
    g.add_node(1, "node1")
    g.add_edge(2, "node1", "node1")

    running = constant_embedding.start(7341)

    embeddings = OpenAIEmbeddings(api_base="http://localhost:7341")
    v_cache = VectorCache(embeddings)
    vg = g.vectorise(v_cache)

    node_docs = vg.nodes_by_similarity(query="whatever", limit=10).get_documents()
    assert len(node_docs) == 1
    assert node_docs[0].content == "Node node1 has the following properties:\n"

    edge_docs = vg.edges_by_similarity(query="whatever", limit=10).get_documents()
    assert len(edge_docs) == 1
    assert (
        edge_docs[0].content
        == "There is an edge from node1 to node1 with events at:\n- Jan 1 1970 00:00\n"
    )

    running.stop()
