[tox]
requires =
    tox>=4
env_list = base, export, benchmark, examples, docs, auth, timezone, df_extras

# MATURIN_PEP517_ARGS
[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
extras =
    tox
    all, storage, auth, df_extras, timezone: test
    export: export
    all: all
pass_env =
    DISK_TEST_MARK
    MAX_MEMORY_BYTES

    # cargo llvm-cov environment variables:
    LLVM_PROFILE_FILE
    RUSTC_WRAPPER
    CARGO_LLVM_COV
    CARGO_LLVM_COV_SHOW_ENV
    CARGO_LLVM_COV_TARGET_DIR
    CARGO_LLVM_COV_BUILD_DIR
    __CARGO_LLVM_COV_RUSTC_WRAPPER
    __CARGO_LLVM_COV_RUSTC_WRAPPER_RUSTFLAGS
    __CARGO_LLVM_COV_RUSTC_WRAPPER_CRATE_NAMES
    CFLAGS
    CXXFLAGS
    RUSTFLAGS

[testenv:.pkg]
set_env =
    # Override from environment if set, else use the default "build-fast" profile.
    MATURIN_PEP517_ARGS={env:MATURIN_PEP517_ARGS:--features test --profile build-fast}
pass_env =
    # cargo llvm-cov environment variables:
    LLVM_PROFILE_FILE
    RUSTC_WRAPPER
    CARGO_LLVM_COV
    CARGO_LLVM_COV_SHOW_ENV
    CARGO_LLVM_COV_TARGET_DIR
    CARGO_LLVM_COV_BUILD_DIR
    __CARGO_LLVM_COV_RUSTC_WRAPPER
    __CARGO_LLVM_COV_RUSTC_WRAPPER_RUSTFLAGS
    __CARGO_LLVM_COV_RUSTC_WRAPPER_CRATE_NAMES
    CFLAGS
    CXXFLAGS
    RUSTFLAGS

[testenv:export]
commands = pytest {posargs} {tty:--color=yes} tests/test_export.py

[testenv:timezone]
commands = pytest {posargs} {tty:--color=yes} tests/test_timezone.py

[testenv:base]
commands = pytest {posargs} --nbmake --nbmake-timeout=1200 {tty:--color=yes} tests/test_base_install

[testenv:df_extras]
commands = pytest {tty:--color=yes} {posargs} --nbmake --nbmake-timeout=1200 {tty:--color=yes} tests/test_ingestion_equivalence_df.py

[testenv:auth]
commands = pytest {posargs} tests/test_auth.py

[testenv:vectors]
commands = pytest {posargs} tests/test_vectors

[testenv:all]
commands = pytest {posargs} --nbmake --nbmake-timeout=1200 {tty:--color=yes} tests

[testenv:examples]
deps =
    ipywidgets
    matplotlib
commands = pytest {posargs} --nbmake --nbmake-timeout=1200 {tty:--color=yes} ../examples/python/socio-patterns/example.ipynb

[testenv:benchmark]
commands = pytest tests/test_graph_benchmarks.py

[testenv:docs]
deps =
    -r ../docs/requirements.txt
change_dir = ../docs/user-guide
env_tmp_dir = ../docs/user-guide/.idea
commands =
    pytest {posargs} --markdown-docs -m markdown-docs --markdown-docs-syntax=superfences
