[package]
edition = "2021"
name = "flux-capacitor"
version = "0.1.0"
rust-version = "1.67.1"

[dependencies]
raphtory = { path = "../raphtory" }
raphtory-io = { path = "../raphtory-io" }

dotenv = "0.15.0"
serde = {version = "1.0.147", features = ["derive"]}

axum = "0.6"
tokio = {version = "1.18.2", features = ["full"]}

async-graphql = "5"
async-graphql-axum = "5"

futures-util = "0.3.0"
async-stream = "0.3.0"

metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
opentelemetry = {version = "0.18.0", features = ["rt-tokio"]}
opentelemetry-jaeger = {version = "0.17.0", features = ["rt-tokio"]}
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = {version = "0.3.16", features = ["std", "env-filter"]}