{
 "title": "Raphtory Basics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "tempo" },
   {
    "name": "service_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name = \"${service_name}\" && name =~ \"addEdge|addEdges|deleteEdge|graph|updateGraph|addNode|node|nodes|edge|edges\"} | avg_over_time(duration) by (name)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "P95 duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name = \"${service_name}\" && name =~ \"addEdge|addEdges|deleteEdge|graph|updateGraph|addNode|node|nodes|edge|edges\"} | quantile_over_time(duration, .95) by (name)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name = \"${service_name}\" && name =~ \"addEdge|addEdges|deleteEdge|graph|updateGraph|addNode|node|nodes|edge|edges\"} | rate() by (name)",
     "tableType": "traces"
    }
   ]
  }
 ]
}