[build-system]
requires = ["setuptools","requests","packaging"]
build-backend = "backend"
backend-path = ["_custom_build","pyraphtory_jvm"]

[project]
name = "pyraphtory_jvm"
authors = [{name="Haaroon Yousaf"},{name="Lucas Jeub"}]
maintainers = [{email="admin@pometry.com"}]
version = "0.1.4"
description = "Bootstrap JRE and IVY installer for Pyraphtory"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    'Development Status :: 1 - Planning',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: BSD License',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
]

[project.urls]
homepage = 'https://github.com/raphtory/raphtory'

[tool.setuptools]
packages = ["pyraphtory_jvm"]
include-package-data = true
