name: pyraphtory
channels:
  - conda-forge
  - defaults
dependencies:
  - libcxx=12.0.0
  - libffi>=3.3
  - make=4.3
  - openjdk=11.0.9.1
  - openssl>=1.1.1q
  - pip>=21.2.4
  - python=3.9.15
  - python_abi>=3.9
  - sbt=1.6.2
  - setuptools>=61.2.0
  - wheel>=0.37.1
  - pip:
      - poetry==1.2.0
      - pemja>=0.2.6
      - cloudpickle>=0.4
      - pandas>=1.4.3
      - matplotlib
      - pyvis
      - scipy
      - seaborn
      - py4j=0.10
      - requests>=2.28.1
      - parsy>=2.0
  - pip:
      - --extra-index-url https://test.pypi.org/simple/
      - pyraphtory_jvm==0.2.0a7
      - pyraphtory==0.2.0a7