name: 🚀🦀 Publish Rust crates to crates.io
on:
  workflow_dispatch:
    inputs: &inputs
      base:
        description: Branch/tag/commit to publish from
        type: string
        default: master
      dry_run:
        description: If selected will not publish to crates.io
        type: boolean
        default: false
      crates:
        description: crate names to publish, i.e. '-p raphtory -p raphtory-graphql' (all by default). Use '--workspace' or leave empty for the full default list.
        type: string
        default: -p raphtory-graphql -p raphtory-api -p raphtory-core -p raphtory -p db4-graph -p db4-storage -p raphtory-api-macros -p raphtory-itertools -p raphtory-storage

  workflow_call:
    inputs: *inputs

permissions:
  contents: read

jobs:
  release-rust:
    name: Release Rust package to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Check if user has write access
        uses: lannonbr/repo-permission-check-action@2.0.0
        with:
          permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.base }}
      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.95.0"
      - name: Publish crates to crates.io (idempotent)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: make publish-crates CRATES="${{ inputs.crates }}"
