name: Docs
on:
  push:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  buildingdocs:
    name: "Triggering ReadTheDocs server build"
    runs-on: ubuntu-latest
    steps:
      - name: Run docs tests
        run: make run-docs-tests
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
