name: (Manual) Release Docker Hub
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to open PR against'
        type: 'string'
        default: 'master'
      dry_run:
        description: 'DRY RUN: If true, will not publish the release to PyPI/crates/Docker Hub but will release to GitHub'
        type: boolean
        default: false

jobs:
  release-rust:
    name: Release rust docker image
    uses: ./.github/workflows/_release_docker.yml
    secrets: inherit
    with:
      base: ${{ inputs.base }}
  release-python:
    name: Release python docker image
    uses: ./.github/workflows/_release_docker.yml
    secrets: inherit
    with:
      base: ${{ inputs.base }}
      python: true
