name: (Manual) Release Rust
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to run the release from'
        type: 'string'
        default: 'master'
      dry_run:
        description: 'If true will not publish to crates.io'
        type: boolean
        default: false
      raphtory-api:
        description: 'Publish raphtory-api'
        type: boolean
        default: true
      pometry-storage:
        description: 'Publish pometry-storage'
        type: boolean
        default: true
      raphtory-core:
        description: 'Publish raphtory-core'
        type: boolean
        default: true
      raphtory-storage:
        description: 'Publish raphtory-storage'
        type: boolean
        default: true
      raphtory:
        description: 'Publish raphtory'
        type: boolean
        default: true
      raphtory-graphql:
        description: 'Publish raphtory-graphql'
        type: boolean
        default: true

jobs:
  call-release-rust-workflow:
    name: _Release 2 - Publish Rust package to crates.io
    uses: ./.github/workflows/_release_rust.yml
    with:
      base: ${{ inputs.base }}
      dry_run: ${{ inputs.dry_run == true }}
      raphtory-api: ${{ inputs.raphtory-api == true }}
      pometry-storage: ${{ inputs.pometry-storage == true }}
      raphtory-core: ${{ inputs.raphtory-core == true }}
      raphtory-storage: ${{ inputs.raphtory-storage == true }}
      raphtory: ${{ inputs.raphtory  == true }}
      raphtory-graphql: ${{ inputs.raphtory-graphql == true }}
    secrets: inherit
