name: (Manual) Release Github
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to open PR against'
        type: 'string'
        default: 'master'
      dry_run:
        description: 'DRY RUN: If true will not publish the release to pypi/crates but will release to github'
        type: boolean
        default: false

jobs:
  call-release-github-workflow:
    name: _Release 4 - Publish to Github
    uses: ./.github/workflows/_release_github.yml
    secrets: inherit
