name: Build image using Docker Build Cloud
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'github ref to build image from'
        type: 'string'
      tag:
        description: 'tag for the docker image'
        type: string
        required: true
      python:
        type: boolean
        description: Wether to build the python version of the image
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base }}

      - name: Read rust version
        run: echo "RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].rust_version')" >> $GITHUB_ENV

      - name: Write dockerfile path
        run: |
          if [ "${{ inputs.python }}" = "true" ]; then
            echo "DOCKERFILE_PATH=python.Dockerfile" >> $GITHUB_ENV
          else
            echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "pometry/raphtory" # for example, "acme/default"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: RUST_VERSION=${{ env.RUST_VERSION }}
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "pometry/raphtory:${{ inputs.tag }}"
