name: (Manual) Release Rust
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to open PR against'
        type: 'string'
        default: 'master'
      dry_run:
        description: 'DRY RUN: If true will not publish the release to pypi/crates but will release to github'
        type: boolean
        default: false

jobs:
  call-release-rust-workflow:
    name: _Release 2 - Publish Rust package to crates.io
    uses: ./.github/workflows/_release_rust.yml
    secrets: inherit
