name: (Manual) Release Rust
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to run the release from'
        type: 'string'
        default: 'master'
      dry_run:
        description: 'If true will not publish to crates.io'
        type: boolean
        default: false

jobs:
  call-release-rust-workflow:
    name: _Release 2 - Publish Rust package to crates.io
    uses: ./.github/workflows/_release_rust.yml
    with:
      base: ${{ inputs.base }}
      dry_run: ${{ inputs.dry_run == true }}
    secrets: inherit
