# this workflow checks out the code, and installs nightly build of cargo and runs a cargo +nightly fmt --all -- --check and fails workflow if any code is not formatted
#

name: Rust format check
on:
  workflow_call:
    inputs:
      fail_if_not_formatted:
        type: boolean
        default: true
        required: false
        description: "Fail the workflow if any code is not formatted"

jobs:
  rust-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup nightly rust
        run: |
          rustup toolchain install nightly --allow-downgrade -c rustfmt
      - name: Run rust format check
        run: |
          if [ ${{ inputs.fail_if_not_formatted }} == true ]; then
              cargo +nightly fmt --all -- --check
          else
              cargo +nightly fmt --all -- --check || true
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pymy networkx pyvis maturin

      - name: Run make tidy-public
        run: make tidy-public

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Uncommitted changes detected after tidy-public. Did you forget to run it?"
            git status
            git diff
            exit 1
          else
            echo "✅ No uncommitted changes after tidy-public."
          fi