name: Run scala & python test
on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string

jobs:
  test:
    name: "test_scala_python"
    strategy:
      fail-fast: false
      matrix:
        runners: ['ubuntu-20.04']
        containers: ["eclipse-temurin:11.0.12_7-jdk"]
        python-version: ["3.9"]
        sbt: [1.6.2]
    runs-on: ${{ matrix.runners }}
    container:
      image: ${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Zookeeper
        run: |
          export ZK_VERSION=3.8.0 && \
          cd /usr/local/bin && \
          curl -L "https://dlcdn.apache.org/zookeeper/zookeeper-${ZK_VERSION}/apache-zookeeper-${ZK_VERSION}-bin.tar.gz" -o apache-zookeeper-${ZK_VERSION}-bin.tar.gz && \
          tar xf apache-zookeeper-${ZK_VERSION}-bin.tar.gz && \
          rm -rf apache-zookeeper-${ZK_VERSION}-bin.tar.gz
      - name: Create Zookeeper Config
        run: mv /usr/local/bin/$(ls /usr/local/bin|grep apache-zookeeper|grep -v "tar.gz"|sort|tail -1)/conf/zoo_sample.cfg /usr/local/bin/$(ls /usr/local/bin|grep apache-zookeeper|grep -v "tar.gz"|sort|tail -1)/conf/zoo.cfg
      - name: Start Zookeeper
        run: /usr/local/bin/$(ls /usr/local/bin|grep apache-zookeeper|grep -v "tar.gz"|sort|tail -1)/bin/zkServer.sh start &
      - name: create blank cred file
        run: mkdir -p $HOME/.sbt && touch $HOME/.sbt/sonatype_credentials
      - name: Get sbt package
        run: apt-get update && apt-get install unzip && curl -L "https://github.com/sbt/sbt/releases/download/v${{ matrix.sbt }}/sbt-${{ matrix.sbt }}.zip" -o sbt-${{ matrix.sbt }}.zip && unzip sbt-${{ matrix.sbt }}.zip
      - name: Build Raphtory Jars
        run: |
          export PATH=$(pwd)/sbt/bin:$PATH
          apt-get update && apt-get install make
          echo "core / Compile / logLevel := Level.Error" >> build.sbt
          echo "deploy / Compile / logLevel := Level.Error" >> build.sbt
          make gh-sbt-build
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and nbmake
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry nbmake tox pytest-xdist
      - name: Install pyraphtory_jvm
        run: cd python/pyraphtory_jvm && python setup.py sdist && python -m pip install dist/pyraphtory_jvm-*.tar.gz
      - name: Run pyraphtory_jvm test fam
        run: cd python/pyraphtory_jvm && tox -p -o
      - name: Install pyraphtory
        run: cd python/pyraphtory && poetry build && poetry install
      - name: Run pyraphtory tests
        run: cd python/pyraphtory && poetry run pytest -n=auto
      - name: Run notebook tests
        run: cd examples && pytest --nbmake -n=auto
      - name: Run doc compile check
        run: | 
          export PATH=$(pwd)/sbt/bin:$PATH
          apt update && apt install -y pandoc 
          cd docs && python -m pip install -r requirements.txt && apt-get update && apt-get -y install python3-sphinx && make html
      - name: Run Core tests via sbt
        run: |
          export PATH=$(pwd)/sbt/bin:$PATH
          export RAPHTORY_CORE_LOG="ERROR"
          sbt "core/test"
      - name: Run Arrow tests via sbt
        run: |
          export PATH=$(pwd)/sbt/bin:$PATH
          export RAPHTORY_CORE_LOG="ERROR"
          sbt "arrowCore/test"
      - name: Run Connectors tests
        run: |
          export PATH=$(pwd)/sbt/bin:$PATH
          export RAPHTORY_CORE_LOG="ERROR"
          sbt "connectorsAWS/test"
          sbt "connectorsTwitter/test"
          sbt "connectorsTypeDB/test"
        timeout-minutes: 10
