name: Run UI tests
permissions:
  contents: read
on:
  workflow_call:
jobs:
  select-strategy:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.set-matrix.outputs.python-versions }}
    steps:
      - id: set-matrix
        run: |
          echo "python-versions=[\"3.9\",\"3.13\"]" >> $GITHUB_OUTPUT
  ui-test:
    name: Python Tests
    needs: select-strategy
    strategy:
      matrix:
        python: ${{ fromJson(needs.select-strategy.outputs.python-versions) }}
        os: [ ubuntu-latest ]
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: ${{ github.head_ref }}
      - name: Setup SSH for UI tests submodule
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UI_TESTS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Init and update UI tests submodule
        run: |
          git submodule sync
          git submodule update --init --recursive ui-tests
      - uses: ./.github/actions/setup_rust
        name: Setup Rust
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        name: Cargo cache
        with:
          cache-all-crates: true
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Create python venv for Maturin
        run: python -m venv .venv
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build raphtory-python
        uses: PyO3/maturin-action@v1
        with:
          working-directory: python
          command: develop
          sccache: true
          args: --release
      - name: Prepare for testing UI
        working-directory: ui-tests
        run: npm install && npx playwright install --with-deps --only-shell
      - name: Test UI
        run: |
          source .venv/bin/activate
          cd ui-tests
          python test_server.py &
          UI_BASE_URL=http://localhost:1736 npm run test
