name: Test Build Push
on:
  push:
    branches: [ feature/build ]
  pull_request:
    branches: [ feature/build ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get sbt package
      run: wget https://github.com/sbt/sbt/releases/download/v1.3.8/sbt-1.3.8.zip && unzip sbt-1.3.8.zip
    - name: Run SBT tests
      run: cd mainproject && ../sbt/bin/sbt test
    - name: Run SBT assembly
      run: cd mainproject && ../sbt/bin/sbt assembly
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: raphtory-core
        path: mainproject/target/scala-2.12/cluster-assembly-latest.jar
